language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requires_tests.txt"  
  - "pip install docutils"
  - "python setup.py build_ext --inplace"
script:
  - pytest --cov=.
  - codecov
  - python setup.py check --restructuredtext --strict
  - rst2html.py --halt=2 README.rst >/dev/null
